before_install: npm install -g grunt-cli
before_script:
  - npm prune
  - npm install
script:
  - grunt
  - npm run test:single
  # - npm run check-coverage
after_success:
  - npm run report-coverage

language: node_js
node_js:
  - "5.6.0"

cache:
  directories:
    - node_modules

services:
  - mongodb

# Compiler
compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
